# -*- coding: utf-8 -*-
"""Blurb italiani degli stili BJCP. Chiave = codice ufficiale (es. "3B") o,
per gli stili storici non numerati, il nome ufficiale."""

BLURBS = {
    "10A": "Birra di frumento bavarese chiara, molto gasata, dal profilo di banana e chiodi di garofano del lievito. Il 4-vinilguaiacolo e l'isoamil acetato non sono difetti: sono lo stile.",
    "10B": "Weissbier scura, con banana e chiodi di garofano sostenuti da pane tostato e caramello. Corpo cremoso e finale leggero: la versione invernale della Weissbier.",
    "10C": "Birra di frumento forte che unisce il lievito della Weissbier alla ricchezza del Bock. Esiste chiara e scura, e copre sia la forza del Bock sia quella del Doppelbock.",
    "11A": "Bitter inglese di bassa gradazione, pensata per la sessione: amaro erbaceo, corpo snello, servita dalla cask a 11-13 °C. L'amaro c'è, ma la beva conta di più.",
    "11B": "Il gradino intermedio della scala Bitter: più corpo e malto dell'Ordinary, amaro sempre sostenuto. Il nome «best» indica la gradazione, non la qualità.",
    "11C": "Bitter inglese di forza media o medio-alta, con equilibrio variabile fra malto e luppolo. È la fascia più larga della famiglia: ogni birraio la interpreta a modo suo.",
    "12A": "Ale britannica chiara e luppolata, nata come birra estiva da bere fresca. Più beverina della Bitter e con luppoli moderni: il ponte fra la tradizione inglese e la pale ale americana.",
    "12B": "Ale australiana chiara e molto gasata, dal corpo pieno ma finale asciutto. Coopers la produce dal 1862: luppolo terroso e frutta a nocciolo per un clima caldo.",
    "12C": "IPA inglese: amara, ben attenuata, secca, con aroma di luppoli britannici. Più terrosa e meno fruttata di quella americana, discende dalle birre d'esportazione di Burton upon Trent.",
    "13A": "Ale inglese scura e leggera, maltata e bevibile in quantità. L'amaro è basso e la tostatura delicata: era la birra quotidiana dell'operaio inglese.",
    "13B": "Ale inglese bruna, caramellata e maltata, senza la tostatura della Porter. Equilibrata e saporita, di solito un po' più forte della media britannica.",
    "13C": "Porter inglese di forza media, bruna scura, con tostato contenuto e note di cioccolato e caramello. È la madre della Stout, nata per gli scaricatori dei mercati londinesi.",
    "14A": "Ale scozzese leggera, maltata, con caramello, tostato e frutta. Una punta di tostatura asciutta tiene a bada il residuo dolce: 60 scellini, nella vecchia nomenclatura.",
    "14B": "Ale scozzese di bassa gradazione, morbida e maltata, con caramello e frutta leggera. Corrisponde ai vecchi «70 scellini».",
    "14C": "Ale scozzese di forza media, maltata e rotonda, con caramello e frutta. Gli «80 scellini» della nomenclatura storica.",
    "15A": "Ale irlandese rossa, facile da bere, con caramello leggero, biscotto e una punta di tostatura in finale. Può pendere sul dolce o sul secco: entrambe le letture sono corrette.",
    "15B": "Stout irlandese nera, dal tostato di caffè e dall'amaro variabile. La Guinness è leggera di corpo e un filo acida: la reputazione di «pesante» è un falso storico.",
    "15C": "Stout irlandese più forte e piena, con tostato di caffè e cioccolato e una certa complessità maltata. È la versione da bottiglia, non da spillatura a nitro.",
    "16A": "Stout molto scura, dolce e piena, con tostato leggero che ricorda caffè e crema. Il lattosio, zucchero non fermentabile, è ciò che la rende dolce.",
    "16B": "Stout scura e tostata con avena, che aggiunge corpo e una morbidezza setosa. L'avena non dà sapore: dà texture.",
    "16C": "Stout molto scura e dolce, fruttata e di forza moderata, con tostato morbido senza asprezza. Nata per i mercati caldi del Commonwealth, è pensata per essere bevuta fresca.",
    "16D": "Stout molto scura e forte, secca, con tostatura importante. Brassata per l'esportazione con più luppolo e alcol: la versione caraibica è la più nota.",
    "17A": "Ale britannica forte, da invecchiamento in bottiglia, con maltosità, frutta e calore alcolico. Categoria larga: dentro ci sta quasi tutto ciò che è forte e inglese.",
    "17B": "Ale inglese forte e maltata, invecchiata, con note di sherry e frutta secca. La maturazione è parte del profilo, non un incidente.",
    "17C": "Ale scozzese forte, dolce e maltata, con caramello, toffee e frutta, corpo pieno e alcol caldo. Il torbato scozzese era leggero e accidentale, non cercato.",
    "17D": "Barley wine inglese: forte, riccamente maltato, con frutta e luppolo. Da meditazione, in bicchiere piccolo, meglio se invecchiato.",
    "18A": "Ale americana bionda e accessibile, orientata al malto, con frutta e luppolo leggeri. È la porta d'ingresso della craft beer americana.",
    "18B": "Pale ale americana di forza media, luppolata ma con malto di supporto. Sierra Nevada (1980) l'ha codificata: è il punto di partenza della rivoluzione craft.",
    "19A": "Ale americana ambrata, luppolata, con caramello maltato. L'equilibrio varia molto: c'è chi la fa maltata e chi aggressivamente luppolata.",
    "19B": "Birra ambrata e tostata, fermentata con lievito da lager a temperatura alta. Lo steam beer di San Francisco: Anchor la produce dal 1896.",
    "19C": "Ale americana bruna, maltata ma luppolata, con cioccolato e caramello. Il luppolo completa il malto invece di combatterlo.",
    "1A": "Lager americana leggerissima, altamente gasata e quasi senza sapori, pensata per essere bevuta ghiacciata. Mais o riso alleggeriscono il corpo: è la birra che ha separato per sempre il mercato di massa dalla tradizione europea.",
    "1B": "Lager pallida, neutra e ben attenuata, con amaro basso e carbonazione alta. Il suo pregio è non avere difetti, non avere carattere.",
    "1C": "Ale americana chiara brassata con lievito da lager o a fermentazione mista: pulita, secca, molto gasata. Il nome non significa «cremosa»: è un'ale che imita la lager, nata nello stato di New York prima del Proibizionismo.",
    "1D": "Birra di frumento americana dal lievito neutro: niente banana né chiodi di garofano. Anchor la produce dal 1984; è il ponte fra la Weissbier bavarese e la sensibilità americana del luppolo.",
    "20A": "Porter americana, maltata e amara, spesso luppolata, con tostato e cioccolato. Più decisa della cugina inglese.",
    "20B": "Stout americana forte e molto tostata, amara e luppolata. Luppolo americano e tostatura spingono nella stessa direzione.",
    "20C": "Stout imperiale: intensa, molto forte, molto scura, con tostato bruciato e frutta scura. Malgrado l'intensità deve essere armoniosa, non un «hot mess»: a volte serve l'invecchiamento.",
    "21A": "IPA americana: luppolata e amara, di forza media, con finale asciutto e malto pulito di supporto. È il banco di prova di ogni luppolo moderno.",
    "21B": "IPA speciale: stessa asciuttezza e stesso bilanciamento luppolato dell'americana, ma più scura. I malti scuri aggiungono supporto, non tostatura bruciata.",
    "21C": "IPA torbida e succosa, con frutta intensa, corpo morbido e amaro percepito più basso. La torbidità è voluta: proteine e luppolo, non lievito in sospensione.",
    "22A": "IPA doppia: intensamente luppolata e forte, ma senza la ricchezza maltata del barley wine. Deve mostrare la forza e restare beverina.",
    "22B": "Ale americana forte e maltata, nello spazio fra barley wine, Double IPA e Red IPA. Malta e luppolo forti ma in equilibrio.",
    "22C": "Barley wine americano: molto forte, maltato e luppolato, con corpo pieno e finale caldo. Da sorseggiare, con il luppolo che contrattacca il malto.",
    "22D": "Barley wine di frumento: molto forte, dal corpo snello ma ricco di pane e frumento. L'enfasi è sul grano, poi su malto, luppolo e alcol.",
    "23A": "Birra di frumento acida di Berlino, leggerissima e molto gasata, con acidità lattica pulita. I berlinesi la bevono con sciroppo di lampone o aspersio: Napoleone la chiamò «lo champagne del nord».",
    "23B": "Ale rossa delle Fiandre, acida e fruttata, invecchiata in botte di rovere. Il finale tannica e secco ricorda un vino rosso d'annata: Roeselare è la capitale.",
    "23C": "Ale bruna acida delle Fiandre orientali, maltata, con caramello e cioccolato e alcol spesso sostenuto. Più maltata e meno acida della Flanders Red.",
    "23D": "Lambic: birra di frumento a fermentazione spontanea della valle della Senna, acida e funky, servita tradizionalmente senza gas. Nessun lievito aggiunto: raffredda in coolship e fermenta con Brettanomyces.",
    "23E": "Gueuze: taglio di lambic di 1, 2 e 3 anni, rifermentato in bottiglia. La «champagne di Bruxelles» — secca, acidissima, con carbonazione finissima.",
    "23F": "Lambic alla frutta: kriek, framboise, cassis. La frutta fermenta nel lambic e ne accentua l'acidità invece di addolcirla.",
    "23G": "Gose: birra di frumento di Goslar, acida e salata, con coriandolo. Rinata negli ultimi vent'anni, è il fossile vivente della tradizione tedesca acida.",
    "24A": "Bianca belga di grano non maltato, coriandolo e scorza d'arancia amara. Hoegaarden l'ha resuscitata nel 1966 dopo decenni di oblio.",
    "24B": "Ale belga di forza media, ambrata e maltata, con frutta e tostato leggero. Meno aggressiva di altre belghe: equilibrio, non eccesso.",
    "24C": "Birra artigianale francese, forte e maltata, maturata a freddo («da conservare»). Esiste bionda, ambrata o bruna; tutte maltate ma asciutte.",
    "25A": "Ale belga bionda, di forza moderata, con lievito agrumato e speziato, palato morbido e finale asciutto. È la sorella minore della Strong Golden.",
    "25B": "Saison: ale belga rinfrescante, molto attenuata, luppolata e amara, dal finale secchissimo. Lievito fruttato, speziato, a volte fenolico; nasce come birra dei contadini dell'Hainaut.",
    "25C": "Ale belga bionda molto forte, attenuata e fruttata più che speziata. Duvel dal 1871: lo zucchero candito alleggerisce il corpo e alza l'alcol.",
    "26A": "Birra da tavola di monastero, bionda, amara e luppolata, molto secca e gasata. Il carattere del lievito belga in versione quotidiana.",
    "26B": "Dubbel: ale belga rosso-rame, di forza moderata, maltata e complessa, con frutta scura e alcol leggero. Riferimento: Westmalle Dubbel.",
    "26C": "Tripel: ale belga chiara e forte, speziata e amara, dal finale asciutto. Westmalle la codifica nel 1934; va servita nel calice, non nella pinta.",
    "26D": "Ale belga scura molto forte, con maltosità, frutta scura e spezie. È la Quadrupel dei trappisti: complessa, ricca, pericolosa.",
    "28A": "Birra con Brettanomyces: più secca e fruttata della base, con note funky variabili. L'acidità è leggera e non lattica.",
    "28B": "Versione acida e funky di uno stile base, fermentata con lieviti e batteri misti. La base dà il vocabolario, la fermentazione mista la grammatica.",
    "28C": "Birra selvatica con frutta, erbe o spezie. La fermentazione mista è il punto di partenza, gli ingredienti aggiunti il tema.",
    "28D": "Birra acida pulita e chiara, con acidità lattica di agrumi e lievi esteri fruttati. Senza Brett: l'acidità è netta, non funky.",
    "29A": "Birra alla frutta: la frutta deve essere evidente ma in equilibrio, senza sembrare un prodotto artificiale. Deve restare riconoscibile come birra.",
    "29B": "Birra con frutta e spezie insieme, entrambe percepibili e bilanciate. L'unione riesce solo se nessuna delle due copre l'altra.",
    "29C": "Birra con frutta e zuccheri aggiunti: entrambi evidenti e in equilibrio. La frutta dà aroma, lo zucchero corpo e alcol.",
    "29D": "Birra all'uva: un incrocio fra vino spumante e birra neutra, in cui l'aroma del vitigno si fonde con luppolo e lievito. Può essere rinfrescante o complessa.",
    "2A": "Lager chiara internazionale, ben attenuata e senza spigoli, spesso prodotta con adjunzioni. Raccoglie le lager commerciali esportate: competenti, dissetanti, dimenticabili.",
    "2B": "Lager ambrata morbida, con caramello e tostato leggeri e amaro contenuto. È la Vienna o la Märzen reinterpretata su scala industriale multinazionale.",
    "2C": "Versione scura e più dolce della lager internazionale, con corpo e sapore poco maggiori e amaro sempre basso. Il colore viene dal malto scuro, non dalla tostatura: niente caffè.",
    "30A": "Birra con spezie, erbe o verdure: il carattere aggiunto deve essere evidente ma in equilibrio. Deve restare una birra, non un infuso.",
    "30B": "Birra autunnale speziata, maltata e di corpo moderato, con finale leggermente caldo. Evoca il raccolto e il Ringraziamento: zucca, cannella, noce moscata.",
    "30C": "Birra invernale più forte e scura, speziata, dal corpo ricco e finale caldo. È la birra delle feste: chiodi di garofano, arancia, cannella.",
    "30D": "Birra con spezie, erbe o verdure più zuccheri aggiunti: entrambi evidenti e bilanciati. La spezia dà il carattere, lo zucchero il corpo.",
    "31A": "Birra base arricchita con cereali alternativi (segale, avena, grano saraceno, riso). Il carattere dipende dal cereale scelto: la base resta riconoscibile.",
    "31B": "Birra con zuccheri alternativi (miele, melassa, sciroppo d'acero). Lo zucchero deve essere evidente e in equilibrio, senza coprire la birra.",
    "32A": "Stile classico con malto affumicato: il fumo completa malto e luppolo della base. L'equilibrio è la chiave, non l'intensità del fumo.",
    "32B": "Stile speciale affumicato: il fumo si aggiunge a una base già speciale (frutta, spezie, cereali alternativi). Deve restare armoniosa.",
    "33A": "Stile classico affinato in legno, con il carattere del contenitore — quercia, vaniglia, tostato — a completare la base. Malti e luppoli dello stile di partenza restano riconoscibili: il legno aggiunge, non copre.",
    "33B": "Stile speciale affinato in botte che ha contenuto alcol, con il carattere del liquore precedente (bourbon, rum, vino) a integrarsi con la base. È la famiglia delle barrel-aged stout e delle birre da meditazione.",
    "34A": "Birra commerciale speciale, giudicata secondo la descrizione dichiarata dal produttore. Categoria di servizio per ciò che non entra altrove.",
    "34B": "Birra che combina stili diversi: il risultato deve essere armonioso e bilanciato. La somma deve avere senso, non essere un collage.",
    "34C": "Birra sperimentale: tecniche o ingredienti nuovi, senza uno stile di riferimento. Deve essere un'esperienza unica, nel bene e nel male.",
    "3A": "Lager ceca chiara, leggera e luppolata, più beverina della Premium Pils: stesso vocabolario di Saaz e stessa maltosità, volume abbassato. In Repubblica Ceca si chiama světlé výčepní pivo.",
    "3B": "La Pilsner di Plzeň: maltosità complessa, amaro di Saaz lungo e rotondo, finale che non finisce mai. Il decotto di mosto è ciò che dà la profondità di pane che le versioni semplificate non hanno.",
    "3C": "Lager ambrata ceca, maltata, con luppolatura da bassa a sostenuta. Polotmavé: il colore è quello del miele scuro e l'equilibrio può pendere dal pane biscottato al caramello.",
    "3D": "Lager scura ceca, ricca e maltata, con tostatura variabile da quasi assente a decisa. Tmavé pivo: può somigliare a una Dunkel o a una stout leggera, e resta sempre beverina.",
    "4A": "Lager bavarese dorata, dal finale morbido e asciutto, con luppolo appena percettibile. Nata a Monaco nel 1894 per contrastare l'invasione delle Pilsner boeme: la maltosità vince, ma non diventa dolce.",
    "4B": "Lager bavarese chiara e più forte, brassata per l'Oktoberfest moderna. Dal 1990 ha soppiantato la Märzen sui banchi della festa: più chiara, più secca, pericolosamente beverina.",
    "4C": "Bock chiara e forte, con finale ben attenuato che la rende scorrevole. Il luppolo è più presente e il malto meno profondo rispetto agli altri Bock: è la Maibock di maggio.",
    "5A": "Lager tedesca leggera, molto attenuata e a basso contenuto calorico, con amaro e aromi ancora riconoscibili. È la risposta tedesca alla birra «light»: stessa pulizia, meno alcol.",
    "5B": "Ale di Colonia, chiara e brillante, con equilibrio delicato fra malto, frutta e luppolo e finale morbido. Si serve in un cilindro da 0,2 litri (Stange) e solo a Colonia può chiamarsi così.",
    "5C": "Lager dorata di Dortmund, più forte e con corpo maggiore, che bilancia maltosità morbida e amaro deciso. L'acqua solfatica della Ruhr ne esalta il finale luppolato.",
    "5D": "Pils tedesca secca e amara, con aroma di luppolo in primo piano e colore oro brillante. Più asciutta e aggressiva della cugina boema: qui il luppolo è il protagonista, non l'ospite.",
    "6A": "Lager ambrata bavarese, tostata e morbida, con amaro contenuto e finale asciutto. Brassata in marzo e maturata in cantina fino all'autunno: era la birra dell'Oktoberfest prima della Festbier.",
    "6B": "Lager ambrata affumicata con legno di faggio, dal profilo Märzen arricchito di fumo. A Bamberga si beve con lo Schlenkerla: l'affumicato è il punto, non un difetto.",
    "6C": "Lager scura e forte, maltata e tostata, senza dolcezza stucchevole in finale. È il Bock invernale: pane scuro, frutta secca, corpo sostenuto.",
    "7A": "Lager ambrata continentale di forza media, maltata e tostata con eleganza, dall'amaro moderato e finale asciutto. Nata a Vienna nel 1841, è emigrata in Messico dove è diventata la Negra Modelo.",
    "7B": "Ale tedesca di Düsseldorf, ambrata, ben attenuata e amara, con corpo fermo e palato morbido. «Alt» significa vecchio: fermentata più fredda e maturata a lungo, è il ponte fra Ale e Lager.",
    "8A": "Lager scura bavarese, profondamente tostata e di pane, senza note bruciate. È l'opposto della Schwarzbier: qui conta la crosta di pane, non il caffè.",
    "8B": "Lager nera tedesca che unisce tostato morbido e amaro moderato, con corpo leggero e finale asciutto. Il colore inganna: è più leggera e beverina di molte bionde.",
    "9A": "Lager tedesca forte e molto maltata, chiara o scura. I nomi finiscono in -ator (Salvator, Celebrator); i monaci la bevevano come «pane liquido» durante la Quaresima.",
    "9B": "Lager scura forte e viscosa, concentrata congelando la birra e rimuovendo il ghiaccio. L'alcol è alto ma deve scaldare, non bruciare: la tecnica toglie acqua, non sapore.",
    "9C": "Birra scura e forte del Baltico, maltata e calda, con frutta scura e tostato senza note bruciate. Spesso fermentata con lievito da lager: il risultato è una porter dal finale morbido.",
    "Historical Beer: Kellerbier": "Lager tedesca non filtrata e non pastorizzata, servita dal recipiente di maturazione. Più ricca e cremosa della base, con lievito in sospensione: è più uno stile di servizio che uno stile di birra.",
    "Historical Beer: Kentucky Common": "Birra scura americana di Louisville, leggera e dissetante, con mais e un tocco di caramello. Intorno al 1900 era la birra quotidiana del Kentucky: fermentazione pulita, alta carbonazione, servita fresca.",
    "Historical Beer: Lichtenhainer": "Birra di frumento tedesca acida e affumicata della Turingia. L'acidità lattica pulita incontra il fumo di malto: una combinazione insolita, per palati allenati, nel solco delle birre di frumento storiche dell'Europa centrale.",
    "Historical Beer: London Brown Ale": "Brown ale londinese dolce e maltata, di bassa gradazione, con caramello e toffee. Nata nel 1902 come birra da bottiglia, la Mann's ne deteneva oltre il 90% del mercato britannico: oggi è quasi estinta.",
    "Historical Beer: Piwo Grodziskie": "Birra di frumento polacca di Grodzisk, affumicata con legno di quercia e molto amara. Leggera come una Berliner Weisse ma mai acida: fumo e luppolo la rendono unica. Si pronuncia «pivo grow-JEES-kee-uh».",
    "Historical Beer: Pre-Prohibition Lager": "Lager chiara americana del periodo precedente al Proibizionismo, con mais o riso fino al 30% e luppolatura generosa. Della scuola dei birrai tedeschi emigrati: più amara e più ricca di una lager moderna.",
    "Historical Beer: Pre-Prohibition Porter": "Porter americana storica di Filadelfia, adattata dai birrai tedeschi con ingredienti locali. Più morbida e meno amara di una porter moderna, con cioccolato, caramello e zucchero bruciato.",
    "Historical Beer: Roggenbier": "Birra di segale bavarese: di fatto una Dunkles Weissbier con la segale al posto del frumento. La segale porta pepe, corpo e una masticabilità che la rende subito riconoscibile. Nata a Regensburg nel 1988.",
    "Historical Beer: Sahti": "Birra di fattoria finlandese, forte, dolce e viscosa, con segale e ginepro. Non viene bollita: il mosto filtra attraverso rami di ginepro, e il risultato è torbido, denso, con banana da lievito. Almeno 500 anni di tradizione.",
    "X1": "Lager argentina dorata, leggera e beverina, con maltosità delicata e amaro basso. Stile locale riconosciuto dalla BJCP nella sua appendice argentina.",
    "X2": "IPA argentina: luppolata e amara, con luppoli locali e frutta tropicale. Adattamento sudamericano dell'IPA, con lievito pulito e finale secco.",
    "X3": "Birra italiana all'uva: un ponte fra birra e vino, con mosto d'uva o vino aggiunto. Può essere rinfrescante o complessa, e il vitigno deve riconoscersi.",
    "X4": "Birra acida brasiliana con frutta tropicale, leggera e molto dissetante. Nata a Santa Catarina: acidità lattica pulita e frutta fresca in primo piano.",
    "X5": "Pilsner neozelandese: asciutta e dorata, con luppoli del Pacifico dal profilo tropicale, agrumato ed erbaceo. Corpo medio e palato morbido per una birra sorprendentemente beverina.",
}
